version: "3"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    container_name: bank_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 9090
    depends_on:
      - db
    ports:
      - "9090:9090"





