openapi: 3.0.0
info:
  title: API de Lançamentos Bancários
  description: API para realizar lançamentos de débito e crédito em contas de clientes.
  version: 1.0.0
servers:
  - url: https://localhost:8080

tags:
  - name: accounts
    description: Operações relacionadas às contas bancárias
  - name: debug
    description: Endpoints para auxiliar na avaliação da API

paths:
  /accounts/{accountId}/transactions:
    post:
      tags:
        - accounts
      summary: Realiza um ou mais lançamentos (crédito ou débito) em uma conta específica.
      operationId: realizarLancamentos
      parameters:
        - name: accountId
          in: path
          required: true
          description: UUID da conta
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchTransactionRequest'
      responses:
        '200':
          description: Lançamentos processados com sucesso
        '400':
          description: Dados inválidos
        '404':
          description: Conta não encontrada

  /accounts/transfer:
    post:
      tags:
        - accounts
      summary: Realiza uma transferência entre duas contas bancárias.
      operationId: transferirEntreContas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Transferência realizada com sucesso
        '400':
          description: Dados inválidos (exemplo = saldo insuficiente)
        '404':
          description: Conta de origem ou destino não encontrada

  /accounts/{accountId}/balance:
    get:
      tags:
        - accounts
      summary: Retorna o saldo atual de uma conta específica.
      operationId: obterSaldoConta
      parameters:
        - name: accountId
          in: path
          required: true
          description: UUID da conta
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Saldo da conta retornado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    format: double
                    example: 1300.50
        '404':
          description: Conta não encontrada

  /setup-application:
    post:
      tags:
        - debug
      summary: Insere 10 contas na aplicação para realização de testes
      operationId: inserirContasDebug
      responses:
        '200':
          description: Contas inseridas com sucesso

  /accounts:
    get:
      tags:
        - debug
      summary: Retorna todos os dados de todas as contas do sistema.
      operationId: obterTodasContasDebug
      responses:
        '200':
          description: Lista de contas retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountDTO'
        '404':
          description: Nenhuma conta encontrada

components:
  schemas:
    AccountDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID único da conta
          example: "a1fef054-53b5-4c63-bd2e-73e48f4bbfe7"
        holderName:
          type: string
          description: Nome do titular da conta
          example: "João da Silva"
        balance:
          type: number
          format: double
          description: Saldo atual da conta
          example: 1450.75

    TransferRequest:
      type: object
      required:
        - fromAccountId
        - toAccountId
        - amount
      properties:
        fromAccountId:
          type: string
          format: uuid
          description: ID da conta de origem
        toAccountId:
          type: string
          format: uuid
          description: ID da conta de destino
        amount:
          type: number
          format: double
          minimum: 0.01
          example: 150.00
          description: Valor a ser transferido
        description:
          type: string
          example: "Pagamento de aluguel"

    BatchTransactionRequest:
      type: object
      required:
        - transactions
      properties:
        transactions:
          type: array
          description: Lista de lançamentos (créditos e/ou débitos)
          items:
            $ref: '#/components/schemas/TransactionRequest'

    TransactionRequest:
      type: object
      required:
        - type
        - amount
      properties:
        type:
          $ref: '#/components/schemas/TransactionType'
        amount:
          type: number
          format: double
          example: 250.00
          minimum: 0.01
          description: Valor do lançamento (positivo)
        description:
          type: string
          example: "Depósito em dinheiro"
          description: Descrição opcional do lançamento

    TransactionType:
      type: string
      description: Tipo do lançamento bancário
      enum:
        - CREDIT
        - DEBIT